#!/usr/bin/env bash

# Written By Brady Bangasser
# This script is meant to be run on the pi node

source utils.sh

DEBUG="false"
GENERATEDFILEMESSAGE="# Generated by configure-net.sh\n# DO NOT MODIFY\n\n"

BASENAME=$(getconfval cluster_name)
TMPHOSTFILE="hosts.tmp"
TMPDHCPFILE="dchpcd.conf.tmp"
HOSTFILEPATH="host" # will be /etc/hosts
BASEIP="192.168.2."
IPSTART=5

while getopts "mdgb:" flag; do
    case "${flag}" in
        b) BASENAME="$OPTARG" ;;
        m) MASTER='true';;
        g) DEBUG="true" ;;
    esac
done

id=$(getconfval node_id)
master=$(getconfval is_master)
db=$(getconfval is_db)
masters=$()
dbs=$()

# number of nodes

if [ "$master" == "" ]; then
    master="false"
fi

if [ "$db" == "" ]; then
    db="false"
fi

masters=$(getconfval cluster_masters)
masters=(${masters//,/ })

# Start setting the hostname file
printf "%b" "$GENERATEDFILEMESSAGE" > $TMPHOSTFILE

#################
# DO NOT EDIT
#################

printf "%-15s %s\n" "127.0.0.1" "localhost" >> $TMPHOSTFILE
printf "%-15s %s\n" "127.0.0.1" "$BASENAME$id" >> $TMPHOSTFILE
printf "%-15s %s\n" "255.255.255.255" "broadcasthost" >> $TMPHOSTFILE
printf "%-15s %s\n\n" "::1" "localhost" >> $TMPHOSTFILE

#################

i=0

echo "# Master Hosts
" >> $TMPHOSTFILE

for maip in "${masters[@]}"; do
    printf "%-15s %s\n" "$maip" "master$i" >> $TMPHOSTFILE
    ((i++))
done

dbs=$(getconfval cluster_dbs)
dbs=(${dbs//,/ })

i=0

echo "
# DB Hosts
" >> $TMPHOSTFILE
for dbip in "${dbs[@]}"; do
    printf "%-15s %s\n" "$dbip" "db$i" >> $TMPHOSTFILE
    ((i++))
done

non=$(getconfval numberOfNodes)
non=$(($non))

echo "
# Nodes
" >> $TMPHOSTFILE

i=$IPSTART
non=$(($non - 1 + $IPSTART))
hostindex=0

while [ $i -le $non ]; do
    printf "%-15s %s\n" "$BASEIP$i" "$BASENAME$hostindex" >> $TMPHOSTFILE
    ((i++))
    ((hostindex++))
done

# DHCP

printf "%b" "$GENERATEDFILEMESSAGE" > $TMPDHCPFILE

profile_name="node_profile"

echo "interface en0
arping $profile_name
" >> $TMPDHCPFILE

echo "profile $profile_name
static ip_address=$BASEIP$id" >> $TMPDHCPFILE

if [ "$DEBUG" == "false" ]; then

    if [ "$master" == "" ]; then
        sudo touch "/etc/$BASENAME/master"
    fi

    sudo mv $TMPDHCPFILE /etc/dchpcd.conf
    echo "$BASENAME$id" | sudo dd of=/etc/hostname
    sudo mv $TMPHOSTFILE /etc/hosts

    sudo reboot
fi
