#!/usr/bin/env bash

# Written By Brady Bangasser
# This script is meant to be run on the pi node

if ! source utils.sh; then
    echo "I can't find utils.sh :("
    exit 1
fi

DEBUG="false"
GENERATEDFILEMESSAGE="# Generated by configure-net.sh\n# DO NOT MODIFY\n\n"

BASENAME=$(getconfval cluster_name)

if [[ "$BASENAME" == "" ]]; then
    echo "Basename is not defined in the config file"
    exit 1
fi

TMPHOSTFILE="hosts.tmp"
TMPDHCPFILE="dhcpcd.conf.tmp"
HOSTFILEPATH="host" # will be /etc/hosts
BASEIP="192.168.2."
IPSTART=5
ROUTER=1

# DEBUG read from config file
DEBUG=$(getconfval DEBUG)

if [[ "$DEBUG" != "" ]]; then
    DEBUG="true"
else
    DEBUG="false"
fi


while getopts "mdgb:" flag; do
    case "${flag}" in
        b) BASENAME="$OPTARG" ;;
        m) MASTER='true';;
        g) DEBUG="true" ;;
    esac
done

id=$(getconfval node_id)

if [[ "$id" == "" ]]; then
    echo "ID not found in config file"
    exit 1
fi

master=$(getconfval is_master)
db=$(getconfval is_db)

# number of nodes

if [ "$master" == "" ]; then
    master="false"
fi

if [ "$db" == "" ]; then
    db="false"
fi

masters=$(getconfval masters)

if [[ "$masters" == "" ]]; then
    echo "No master nodes defined in config file"
    exit 1
fi

masters=(${masters//,/ })

# Start setting the hostname file
printf "%b" "$GENERATEDFILEMESSAGE" > $TMPHOSTFILE

#################
# DO NOT EDIT
#################

printf "%-15s %s\n" "127.0.0.1" "localhost" >> $TMPHOSTFILE
printf "%-15s %s\n" "127.0.0.1" "$BASENAME$id" >> $TMPHOSTFILE
printf "%-15s %s\n" "255.255.255.255" "broadcasthost" >> $TMPHOSTFILE
printf "%-15s %s\n\n" "::1" "localhost" >> $TMPHOSTFILE

#################

i=0

echo "# Master Hosts
" >> $TMPHOSTFILE

for maip in "${masters[@]}"; do
    printf "%-15s %s\n" "$maip" "master$i" >> $TMPHOSTFILE
    ((i++))
done

dbs=$(getconfval dbs)
dbs=(${dbs//,/ })

i=0

echo "
# DB Hosts
" >> $TMPHOSTFILE
for dbip in "${dbs[@]}"; do
    printf "%-15s %s\n" "$dbip" "db$i" >> $TMPHOSTFILE
    ((i++))
done

non=$(getconfval number_of_nodes)
non=$(($non))

echo "
# Nodes
" >> $TMPHOSTFILE

i=$IPSTART
non=$(($non - 1 + $IPSTART))
hostindex=0

while [ $i -le $non ]; do
    printf "%-15s %s\n" "$BASEIP$i" "$BASENAME$hostindex" >> $TMPHOSTFILE
    ((i++))
    ((hostindex++))
done

# DHCP

printf "%b" "$GENERATEDFILEMESSAGE" > $TMPDHCPFILE

profile_name="node_profile"

ipend=$(($id + $IPSTART))

echo "profile $profile_name
static ip_address=$BASEIP$ipend
static routers=$BASEIP$ROUTER" >> $TMPDHCPFILE

echo "interface eth0
fallback $profile_name
" >> $TMPDHCPFILE

if [ "$DEBUG" == "false" ]; then

    if [ "$master" == "" ]; then
        sudo touch "/etc/$BASENAME/master"
    fi

    sudo mv $TMPDHCPFILE /etc/dhcpcd.conf
    echo "$BASENAME$id" | sudo dd of=/etc/hostname
    sudo mv $TMPHOSTFILE /etc/hosts

    sudo reboot
fi
